version: "3"

services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    restart: always
    networks:
      - backend

  redis:
    image: redis:${REDIS_VERSION}
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    restart: always
    networks:
      - backend

  maven:
    image: maven:${MAVEN_VERSION}
    volumes:
      - ${DATA_PATH_HOST}/maven-repo:/root/.m2
      - ${APP_SRC_PATH}:/project
    working_dir: /project
    networks:
      - backend

  tomcat:
    image: tomcat:8
    ports:
      - "8099:8080"
    volumes:
      - ${APP_SRC_PATH}/target/HelloWebApp.war:/usr/local/tomcat/webapps/ROOT.war
      - ${APP_SRC_PATH}/target/HelloWebApp:/usr/local/tomcat/webapps/ROOT
    depends_on:
      - "mysql"
    networks:
      - backend

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}
  maven:
    driver: ${VOLUMES_DRIVER}